baseURL = "https://blog.neme.site/"
title = "Learning Everyday"
paginate = 10

[params.authors.alex]
  name = "Alex Neme"
  role = "Data Engineer"
  location = "Brazil"
  bio = "Automation, observability, and pipeline builder."
  avatar = "/images/avatar-alex.jpg"
  website = "https://neme.site"
  github = "alexneme"
  linkedin = "alexneme"

[params.authors.enriq]
  name = "Enrique de Andrade Castro"
  avatar = "/images/avatar-enriq.jpg"
  role = "IT Infrastructure | Network Security | Linux | Zabbix | FortiGate"
  location = "Brazil"
  bio = "IT Infrastructure Analyst"
  github = "Enriq4472"
  linkedin = "enrique-de-andrade-castro"


[outputs]
  home = ["HTML","RSS"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1
  [languages."pt-br"]
    languageCode = "pt-BR"
    languageName = "Português (Brasil)"
    weight = 2

[params.giscus]
  repo       = "alexneme/portfolio"
  repoId     = "R_kgDOPgSzWg"
  category   = "General"
  categoryId = "DIC_kwDOPgSzWs4CuVI1"
  lang       = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      block = true
      title = true

baseURL = "https://blog.neme.site/"
canonifyURLs = true
